name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubantu latest
    steps:
      - name: print greetings
        run: echo "Hellp Dear "
      - name: print good bye
        run: echo "Bye Bye "
        
